
package Interfaces;

import Clases.*;

public class Menu extends javax.swing.JFrame {

        
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuSistema = new javax.swing.JMenu();
        jMenuItemCerrarSecion = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuGestionAnimales = new javax.swing.JMenu();
        jMenuItemRegistroAnimales = new javax.swing.JMenuItem();
        jMenuItemConsultarAnimales = new javax.swing.JMenuItem();
        jMenuItemAlimentos = new javax.swing.JMenuItem();
        jMenuItemReporteAnimales = new javax.swing.JMenuItem();
        jMenuGestionAlmacen = new javax.swing.JMenu();
        jMenuItemRegistrarProductos = new javax.swing.JMenuItem();
        jMenuItemReporteProductos = new javax.swing.JMenuItem();
        jMenuGestionZoo = new javax.swing.JMenu();
        jMenuItemZonas = new javax.swing.JMenuItem();
        jMenuItemJaulas = new javax.swing.JMenuItem();
        jMenuGestionEmpleados = new javax.swing.JMenu();
        jMenuItemRegistroEmpleados = new javax.swing.JMenuItem();
        jMenuItemReporteEmpleados = new javax.swing.JMenuItem();
        jMenuProveedores = new javax.swing.JMenu();
        jMenuItemRegistroProv = new javax.swing.JMenuItem();
        jMenuItemReporteProv = new javax.swing.JMenuItem();
        jMenuCartillaMedica = new javax.swing.JMenu();
        jMenuItemRegistrarCartilla = new javax.swing.JMenuItem();
        jMenuCarnetVacuna = new javax.swing.JMenu();
        jMenuItemRegistrarVacuna = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setText("ZOOLOGICO ICEBERG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 440, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/002.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 910, 240));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/0030.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 790, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 490));

        jMenuBar2.setBackground(new java.awt.Color(153, 102, 0));
        jMenuBar2.setForeground(new java.awt.Color(153, 102, 0));
        jMenuBar2.setFocusCycleRoot(true);

        jMenuSistema.setBackground(new java.awt.Color(51, 51, 51));
        jMenuSistema.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenuSistema.setForeground(new java.awt.Color(153, 102, 0));
        jMenuSistema.setText("SISTEMA");

        jMenuItemCerrarSecion.setBackground(new java.awt.Color(153, 102, 0));
        jMenuItemCerrarSecion.setText("CERRAR SESION");
        jMenuItemCerrarSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSecionActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuItemCerrarSecion);

        jMenuItemSalir.setText("SALIR");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuItemSalir);

        jMenuBar2.add(jMenuSistema);

        jMenuGestionAnimales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenuGestionAnimales.setForeground(new java.awt.Color(153, 102, 0));
        jMenuGestionAnimales.setText("GESTION ANIMALES");

        jMenuItemRegistroAnimales.setText("FICHAS REGISTRO ANIMALES");
        jMenuItemRegistroAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroAnimalesActionPerformed(evt);
            }
        });
        jMenuGestionAnimales.add(jMenuItemRegistroAnimales);

        jMenuItemConsultarAnimales.setText("CONSULTAR ANIMALES");
        jMenuItemConsultarAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarAnimalesActionPerformed(evt);
            }
        });
        jMenuGestionAnimales.add(jMenuItemConsultarAnimales);

        jMenuItemAlimentos.setText("ALIMENTAR");
        jMenuItemAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlimentosActionPerformed(evt);
            }
        });
        jMenuGestionAnimales.add(jMenuItemAlimentos);

        jMenuItemReporteAnimales.setText("REPORTE ANIMALES");
        jMenuItemReporteAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReporteAnimalesActionPerformed(evt);
            }
        });
        jMenuGestionAnimales.add(jMenuItemReporteAnimales);

        jMenuBar2.add(jMenuGestionAnimales);

        jMenuGestionAlmacen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenuGestionAlmacen.setForeground(new java.awt.Color(153, 102, 0));
        jMenuGestionAlmacen.setText("GESTION ALMACEN");

        jMenuItemRegistrarProductos.setText("REGISTRAR PRODUCTOS");
        jMenuItemRegistrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarProductosActionPerformed(evt);
            }
        });
        jMenuGestionAlmacen.add(jMenuItemRegistrarProductos);

        jMenuItemReporteProductos.setText("REPORTE PRODUCTOS");
        jMenuItemReporteProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReporteProductosActionPerformed(evt);
            }
        });
        jMenuGestionAlmacen.add(jMenuItemReporteProductos);

        jMenuBar2.add(jMenuGestionAlmacen);

        jMenuGestionZoo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenuGestionZoo.setForeground(new java.awt.Color(153, 102, 0));
        jMenuGestionZoo.setText("GESTIÓN ZOO");

        jMenuItemZonas.setText("ZONAS");
        jMenuItemZonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZonasActionPerformed(evt);
            }
        });
        jMenuGestionZoo.add(jMenuItemZonas);

        jMenuItemJaulas.setText("JAULAS");
        jMenuItemJaulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJaulasActionPerformed(evt);
            }
        });
        jMenuGestionZoo.add(jMenuItemJaulas);

        jMenuBar2.add(jMenuGestionZoo);

        jMenuGestionEmpleados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenuGestionEmpleados.setForeground(new java.awt.Color(153, 102, 0));
        jMenuGestionEmpleados.setText("GESTION EMPLEADOS");

        jMenuItemRegistroEmpleados.setText("REGISTRO USUARIOS");
        jMenuItemRegistroEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroEmpleadosActionPerformed(evt);
            }
        });
        jMenuGestionEmpleados.add(jMenuItemRegistroEmpleados);

        jMenuItemReporteEmpleados.setText("REPORTE USUARIOS");
        jMenuItemReporteEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReporteEmpleadosActionPerformed(evt);
            }
        });
        jMenuGestionEmpleados.add(jMenuItemReporteEmpleados);

        jMenuBar2.add(jMenuGestionEmpleados);

        jMenuProveedores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenuProveedores.setForeground(new java.awt.Color(153, 102, 0));
        jMenuProveedores.setText("PROVEEDORES");

        jMenuItemRegistroProv.setText("REGISTRAR");
        jMenuItemRegistroProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroProvActionPerformed(evt);
            }
        });
        jMenuProveedores.add(jMenuItemRegistroProv);

        jMenuItemReporteProv.setText("REPORTE");
        jMenuItemReporteProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReporteProvActionPerformed(evt);
            }
        });
        jMenuProveedores.add(jMenuItemReporteProv);

        jMenuBar2.add(jMenuProveedores);

        jMenuCartillaMedica.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenuCartillaMedica.setForeground(new java.awt.Color(153, 102, 0));
        jMenuCartillaMedica.setText("CARTILLAS MEDICAS");

        jMenuItemRegistrarCartilla.setText("REGISTRAR");
        jMenuItemRegistrarCartilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarCartillaActionPerformed(evt);
            }
        });
        jMenuCartillaMedica.add(jMenuItemRegistrarCartilla);

        jMenuBar2.add(jMenuCartillaMedica);

        jMenuCarnetVacuna.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenuCarnetVacuna.setForeground(new java.awt.Color(153, 102, 0));
        jMenuCarnetVacuna.setText("CARNETS VACUNA");

        jMenuItemRegistrarVacuna.setText("REGISTRAR");
        jMenuItemRegistrarVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarVacunaActionPerformed(evt);
            }
        });
        jMenuCarnetVacuna.add(jMenuItemRegistrarVacuna);

        jMenuBar2.add(jMenuCarnetVacuna);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemConsultarAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarAnimalesActionPerformed
         LoginInterfaz verventana= new LoginInterfaz();
        verventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemConsultarAnimalesActionPerformed

    private void jMenuItemReporteEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteEmpleadosActionPerformed
       /*ReportePersonal verventana= new ReportePersonal();
        verventana.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_jMenuItemReporteEmpleadosActionPerformed

    private void jMenuItemCerrarSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSecionActionPerformed
       LoginInterfaz verventana= new LoginInterfaz();
        verventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemCerrarSecionActionPerformed

    private void jMenuItemRegistroAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroAnimalesActionPerformed
        RegistroAnimal verventana= new RegistroAnimal();
        verventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemRegistroAnimalesActionPerformed

    private void jMenuItemAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlimentosActionPerformed
         RegistroDieta verventana= new RegistroDieta();
        verventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemAlimentosActionPerformed

    private void jMenuItemReporteAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteAnimalesActionPerformed
     ReporteAnimales verventana= new ReporteAnimales();
        verventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemReporteAnimalesActionPerformed

    private void jMenuItemRegistrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarProductosActionPerformed
        Registros_Productos verventana= new Registros_Productos();
        verventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemRegistrarProductosActionPerformed

    private void jMenuItemReporteProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteProductosActionPerformed
       ReporteProductos verventana= new ReporteProductos();
        verventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemReporteProductosActionPerformed

    private void jMenuItemZonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZonasActionPerformed
       /*Habitad verventana= new Habitad();
        verventana.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_jMenuItemZonasActionPerformed

    private void jMenuItemJaulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJaulasActionPerformed
        /*Jaulas verventana= new Jaulas();
        verventana.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_jMenuItemJaulasActionPerformed

    private void jMenuItemRegistroEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroEmpleadosActionPerformed
        RegistroUsuario verventana= new RegistroUsuario();
        verventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemRegistroEmpleadosActionPerformed

    private void jMenuItemRegistroProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroProvActionPerformed
       /* RegistroProveedores verventana= new RegistroProveedores();
        verventana.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_jMenuItemRegistroProvActionPerformed

    private void jMenuItemReporteProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteProvActionPerformed
      /*  ReporteProveedor verventana= new ReporteProveedor();
        verventana.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_jMenuItemReporteProvActionPerformed

    private void jMenuItemRegistrarCartillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarCartillaActionPerformed
        /*CartillasMedicas verventana= new CartillasMedicas();
        verventana.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_jMenuItemRegistrarCartillaActionPerformed

    private void jMenuItemRegistrarVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarVacunaActionPerformed
         /*CarnetVacuna verventana= new CarnetVacuna();
        verventana.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_jMenuItemRegistrarVacunaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCarnetVacuna;
    private javax.swing.JMenu jMenuCartillaMedica;
    private javax.swing.JMenu jMenuGestionAlmacen;
    private javax.swing.JMenu jMenuGestionAnimales;
    private javax.swing.JMenu jMenuGestionEmpleados;
    private javax.swing.JMenu jMenuGestionZoo;
    private javax.swing.JMenuItem jMenuItemAlimentos;
    private javax.swing.JMenuItem jMenuItemCerrarSecion;
    private javax.swing.JMenuItem jMenuItemConsultarAnimales;
    private javax.swing.JMenuItem jMenuItemJaulas;
    private javax.swing.JMenuItem jMenuItemRegistrarCartilla;
    private javax.swing.JMenuItem jMenuItemRegistrarProductos;
    private javax.swing.JMenuItem jMenuItemRegistrarVacuna;
    private javax.swing.JMenuItem jMenuItemRegistroAnimales;
    private javax.swing.JMenuItem jMenuItemRegistroEmpleados;
    private javax.swing.JMenuItem jMenuItemRegistroProv;
    private javax.swing.JMenuItem jMenuItemReporteAnimales;
    private javax.swing.JMenuItem jMenuItemReporteEmpleados;
    private javax.swing.JMenuItem jMenuItemReporteProductos;
    private javax.swing.JMenuItem jMenuItemReporteProv;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemZonas;
    private javax.swing.JMenu jMenuProveedores;
    private javax.swing.JMenu jMenuSistema;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
