/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Animal;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javafx.scene.control.RadioButton;
import javax.swing.JTextField;

/**
 *
 * @author USUARIO
 */
public class RegistroAnimal extends javax.swing.JFrame {

    /**
     * Creates new form RegistroAnimal
     */
    public static LinkedList<Animal> listaanimal = new LinkedList<Animal>();

    Animal aanimal = null;

    public RegistroAnimal() {
        initComponents();
        this.setLocationRelativeTo(null);

        botones.add(hembra);
        botones.add(macho);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        animal = new javax.swing.JTextField();
        nombrecien = new javax.swing.JTextField();
        nombrevulg = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        origen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        Modificar = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        guardar = new javax.swing.JToggleButton();
        eliminar = new javax.swing.JToggleButton();
        consultar = new javax.swing.JToggleButton();
        buscar = new javax.swing.JTextField();
        jButtonSalir = new javax.swing.JButton();
        fechaingreso = new com.toedter.calendar.JDateChooser();
        fechanacimiento = new com.toedter.calendar.JDateChooser();
        macho = new javax.swing.JRadioButton();
        hembra = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO ANIMAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 190, 50));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Descripcion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("ID Animal:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Nombre Cientifico:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Nombre Vulgar:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Peso:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Edad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Origen:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Sexo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Fecha Ingreso:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Fecha Nacimiento:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalActionPerformed(evt);
            }
        });
        getContentPane().add(animal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 210, -1));

        nombrecien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrecienActionPerformed(evt);
            }
        });
        getContentPane().add(nombrecien, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, -1));

        nombrevulg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrevulgActionPerformed(evt);
            }
        });
        getContentPane().add(nombrevulg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 210, -1));

        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });
        getContentPane().add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 210, -1));

        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 210, -1));

        origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origenActionPerformed(evt);
            }
        });
        getContentPane().add(origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 210, -1));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 330, -1));

        Modificar.setText("MODIFICAR");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));

        jToggleButton2.setText("X");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        consultar.setText("CONSULTAR");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 160, -1));

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir.png"))); // NOI18N
        jButtonSalir.setBorder(null);
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, -1, -1));
        getContentPane().add(fechaingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 190, -1));
        getContentPane().add(fechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 180, -1));

        macho.setText("Macho");
        getContentPane().add(macho, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        hembra.setText("Hembra");
        getContentPane().add(hembra, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalActionPerformed

    private void nombrecienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrecienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrecienActionPerformed

    private void nombrevulgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrevulgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrevulgActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed

    private void edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadActionPerformed

    private void origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origenActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:

        if (animal.getText().isEmpty() || nombrecien.getText().isEmpty() || nombrevulg.getText().isEmpty() || peso.getText().isEmpty() || origen.getText().isEmpty() || descripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "FALTAN DATOS");
        } else {

            String Idanimal = animal.getText();
            String nombre_cientifico = nombrecien.getText();
            String nombrevulgar = nombrevulg.getText();
            String Peso = peso.getText();
            String Edad = edad.getText();
            String Origen = origen.getText();
            String sexo = Sexo();
            Date fecha_ingreso = fechaingreso.getDate();
            Date fecha_naciemiento = fechanacimiento.getDate();
            String Descripcion = descripcion.getText();

            Animal mianimal = new Animal(Idanimal, nombre_cientifico, nombrevulgar, Peso, Edad, Origen,sexo, fecha_ingreso, fecha_naciemiento, Descripcion);

            animal.setText("");
            nombrecien.setText("");
            nombrevulg.setText("");
            peso.setText("");
            edad.setText("");
            origen.setText("");
            descripcion.setText("");
            listaanimal.add(mianimal);

        }

    }//GEN-LAST:event_guardarActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        String buscaranimal = buscar.getText();
        boolean encontrar = false;

        for (int i = 0; i < listaanimal.size(); i++) {
            if (listaanimal.get(i).getIdAnimal().equalsIgnoreCase(buscaranimal)) {
                aanimal = listaanimal.get(i);
                encontrar = true;
            }
        }
        if (encontrar == true) {

            String sexo = aanimal.getSexo();

            animal.setText(aanimal.getIdAnimal());
            nombrecien.setText(aanimal.getNombre_cienti());
            nombrevulg.setText(aanimal.getNombre_vulga());
            peso.setText(aanimal.getPeso());
            edad.setText(aanimal.getEdad());
            origen.setText(aanimal.getOrigen());
            descripcion.setText(aanimal.getDescripcion());

            switch (sexo) {
                case "Macho":
                    macho.setSelected(true);
                    break;
                case "Hembra":
                    hembra.setSelected(true);
                    break;

            }

        } else {
            animal.setText("");
            nombrecien.setText("");
            nombrevulg.setText("");
            peso.setText("");
            edad.setText("");
            origen.setText("");
            descripcion.setText("");

            JOptionPane.showMessageDialog(null, "NO EXISTEN DATOS");

        }
    }//GEN-LAST:event_consultarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(RegistroAnimal.this, "Esta seguro de eliminar esta Animal", "confirmacion", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            try {
                RegistroAnimal.listaanimal.remove(buscar);
                animal.setText("");
                nombrecien.setText("");
                nombrevulg.setText("");
                peso.setText("");
                edad.setText("");
                origen.setText("");
                descripcion.setText("");

                JOptionPane.showMessageDialog(null, "Animal Eliminado");
            } catch (Exception e) {
                System.out.println(e);
            }
        }
        
        

    }//GEN-LAST:event_eliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        if (aanimal != null) {
            String Idanimal = animal.getText();
            String nombre_cientifico = nombrecien.getText();
            String nombrevulgar = nombrevulg.getText();
            String Peso = peso.getText();
            String Edad = edad.getText();
            String Origen = origen.getText();
            String sexo = Sexo();
            Date fecha_ingreso = fechaingreso.getDate();
            Date fecha_naciemiento = fechanacimiento.getDate();
            String Descripcion = descripcion.getText();

            aanimal.setIdAnimal(Idanimal);
            aanimal.setNombre_cienti(nombre_cientifico);
            aanimal.setNombre_vulga(nombrevulgar);
            aanimal.setPeso(Peso);
            aanimal.setEdad(Edad);
            aanimal.setOrigen(Origen);
            aanimal.setSexo(sexo);
            aanimal.setFecha_ingreso(fecha_ingreso);
            aanimal.setFecha_nacimiento(fecha_naciemiento);
            aanimal.setDescripcion(Descripcion);

            animal.setText("");
            nombrecien.setText("");
            nombrevulg.setText("");
            peso.setText("");
            edad.setText("");
            origen.setText("");
            descripcion.setText("");

            aanimal = null;

        } else {
            JOptionPane.showMessageDialog(null, "NO EXISTEN DATOS");
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        Menu remenu = new Menu();
        remenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAnimal().setVisible(true);
            }
        });
    }

    public String Sexo() {
        String eleccion = null;
        if (macho.isSelected()) {
            eleccion = "Macho";
        }
        if (hembra.isSelected()) {
            eleccion = "Hembra";
        } else {
            eleccion = "Sexo no registrado";
        }

        return eleccion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Modificar;
    public static javax.swing.JTextField animal;
    private javax.swing.ButtonGroup botones;
    public static javax.swing.JTextField buscar;
    private javax.swing.JToggleButton consultar;
    public static javax.swing.JTextArea descripcion;
    public static javax.swing.JTextField edad;
    private javax.swing.JToggleButton eliminar;
    private com.toedter.calendar.JDateChooser fechaingreso;
    private com.toedter.calendar.JDateChooser fechanacimiento;
    private javax.swing.JToggleButton guardar;
    private javax.swing.JRadioButton hembra;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JRadioButton macho;
    public static javax.swing.JTextField nombrecien;
    public static javax.swing.JTextField nombrevulg;
    public static javax.swing.JTextField origen;
    public static javax.swing.JTextField peso;
    // End of variables declaration//GEN-END:variables
}
